mxonline_chen/apps/course/urls.py
from django.conf.urls import url


from .views import CourselistView,CoursedetailView,CourselessonView,CommentView,Add_commentView,Video_playView

urlpatterns = [
    # 课程列表页url
    url(r'^list/$', CourselistView.as_view(), name='list'),
    # 课程详情页
    url(r'^detail/(?P<course_id>\d+)/$', CoursedetailView.as_view(), name='detail'),
    # 课程章节页
    url(r'^lesson/(?P<course_id>\d+)/$', CourselessonView.as_view(), name='lesson'),

    # 课程评论
    url(r'^comment/(?P<course_id>\d+)/$', CommentView.as_view(), name='comment'),
    # 添加课程评论
    url(r'^add_comment/$', Add_commentView.as_view(), name='add_comment'),

    # 视频播放url
    url(r'^video/(?P<video_id>\d+)/$', Video_playView.as_view(), name='video_play'),

]

mxonline_chen/apps/organization/urls.py
from django.conf.urls import url

from .views import OrglistView, UseraskView, Org_homeView, Org_courseView, Org_descView,Org_teacherView
from .views import AddfavView,TeacherlistView,TeacherdetailView
urlpatterns = [
    # 课程机构列表页url
    url(r'^list/$', OrglistView.as_view(), name='list'),
    url(r'^addask/$', UseraskView.as_view(), name='add_ask'),
    url(r'^home/(?P<org_id>\d+)/$', Org_homeView.as_view(), name='org_home'),
    url(r'^course/(?P<org_id>\d+)/$', Org_courseView.as_view(), name='org_course'),
    url(r'^desc/(?P<org_id>\d+)/$', Org_descView.as_view(), name='org_desc'),
    url(r'^org_teacher/(?P<org_id>\d+)/$', Org_teacherView.as_view(), name='org_teacher'),

    # 用户收藏
    url(r'^add_fav',AddfavView.as_view(),name='add_fav'),

    # 授课讲师列表页url 配置
    url(r'^teacher/list/$',TeacherlistView.as_view(),name='teacher_list'),

    # 讲师详情页面url 配置
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherdetailView.as_view(),name='teacher_detail')
]

mxonline_chen/apps/users/urls.py
from django.conf.urls import url,include

from .views import UserinfoView,UploadImageView,UpdatePwdView,UpdateEmailView,SendEmailCodeView,MycourseView
from .views import MyfavOrgView,MyfavTeacherView,MyfavCourseView,MymessageView



urlpatterns = [
    # 用户个人中心首页
    url(r'^info/$',UserinfoView.as_view(),name='userinfo'),

    # 用户修改头像
    url(r'^image/upload$',UploadImageView.as_view(), name='image_upload'),

    # 用户修改密码
    url(r'^update/pwd/$',UpdatePwdView.as_view(), name='update_pwd'),

    # 发送邮箱验证码
    url(r'^send_email_code_change/$',SendEmailCodeView.as_view(), name='send_email_code_change'),

    # 用户修改邮箱
    url(r'^update_email/$',UpdateEmailView.as_view(), name='update_email'),

    # 用户中心我的课程
    url(r'^mycourse/$',MycourseView.as_view(),name='mycourse'),

    # 用户中心我的收藏课程机构
    url(r'^myfav/org/$', MyfavOrgView.as_view(), name='myfav_org'),

    # 用户中心我的收藏授课讲师
    url(r'^myfav/teacher/$', MyfavTeacherView.as_view(), name='myfav_teacher'),

    # 用户中心我的收藏公开课程
    url(r'^myfav/couser/$', MyfavCourseView.as_view(), name='myfav_course'),

    # 用户中心，我的消息
    url(r'^mymessage/$',MymessageView.as_view(),name='mymessage')


]

mxonline_chen/extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

mxonline_chen/mxonline_chen/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve

import xadmin
from users.views import IndexView, LoginView, RegisterView, AciveUserView, ForgetPwdView, ResetPwdView, ModifyPwdView,LogoutView
from organization.views import OrglistView
from mxonline_chen.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    # url(r'^login/$',login_chen,name='login'),
    # url(r'^login/$',TemplateView.as_view(template_name='login.html'),name='login'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$', AciveUserView.as_view(), name='user_active'),
    url(r'^forget_pwd/$', ForgetPwdView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<reset_code>.*)/$', ResetPwdView.as_view(), name='reset_pwd'),
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name='modify_pwd'),

    # 课程机构url相关配置
    url(r'^org/',include('organization.urls',namespace='org')),

    # 课程相关url配置
    url(r'^course/',include('course.urls',namespace='course')),

    # 配置上传图片的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # 自定义静态文件路径
    # url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

    # 配置用户个人中心
    url(r'^users/',include('users.urls',namespace='users')),

    # ueditor 富文本编辑器相关url
    url(r'^ueditor/',include('DjangoUeditor.urls' )),

]
#全局404页面配置
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

mxonline_chen/apps/course/models.py
from datetime import datetime

from DjangoUeditor.models import UEditorField
from django.db import models

from organization.models import CourseOrg, Teacher


# Create your models here.

class Course(models.Model):
    """
    课程模型类
    """
    DEGREE = (
        ("cj", "初级"),
        ("zj", "中级"),
        ("gj", "高级"),
    )
    course_org = models.ForeignKey(CourseOrg, verbose_name='课程机构', blank=True, null=True)
    name = models.CharField(max_length=50, verbose_name="课程名")
    desc = models.CharField(max_length=300, verbose_name="课程描述")
    detail = UEditorField(verbose_name="课程详情",width=600, height=300,  imagePath="courses/ueditor/",
                                         filePath="courses/ueditor/", default="")
    is_banner = models.BooleanField(default=False,verbose_name="是否轮播")
    teacher = models.ForeignKey(Teacher, verbose_name="讲师", null=True, blank=True)
    degree = models.CharField(choices=DEGREE, max_length=2, verbose_name='课程难度')
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟)")
    students = models.IntegerField(default=0, verbose_name="学习人数")
    fav_nums = models.IntegerField(default=0, verbose_name="收藏人数")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name="封面图", max_length=100)
    click_nums = models.IntegerField(default=0, verbose_name="点击数")
    category = models.CharField(default="后台开发", verbose_name="课程类别", max_length=20)
    tag = models.CharField(verbose_name="课程标签", max_length=10, default="")
    you_know = models.CharField(verbose_name="课程须知", max_length=300, default="")
    teacher_tell = models.CharField(verbose_name="老师告诉你", max_length=300, default="")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程"
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        # 获取课程章节数
        return self.lesson_set.all().count()
    get_zj_nums.short_description = "章节数"

    def get_learn_users(self):
        # 获取学习用户
        return self.usercourse_set.all()[:5]

    def get_lesson(self):
        # 获取课程章节
        return self.lesson_set.all()

    def __str__(self):
        return self.name


class Lesson(models.Model):
    """
    章节表
    """
    course = models.ForeignKey(Course, verbose_name="课程")
    name = models.CharField(max_length=100, verbose_name="章节")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "章节"
        verbose_name_plural = verbose_name

    def get_lesson_video(self):
        # 获取章节视频
        return self.video_set.all()

    def __str__(self):
        return self.name


class Video(models.Model):
    """
    视频表
    """
    lesson = models.ForeignKey(Lesson, verbose_name="章节")
    name = models.CharField(max_length=100, verbose_name="视频名")
    url = models.CharField(max_length=200, verbose_name="访问地址", default="")
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟)")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    """
    课程资源表
    """
    course = models.ForeignKey(Course, verbose_name="课程")
    name = models.CharField(max_length=100, verbose_name="名称")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name="资源文件", max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

mxonline_chen/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>链接失效</p>

</body>
</html>

mxonline_chen/templates/course_play.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
{{ all_videos.name }}-慕学在线网
{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />

    <link rel="stylesheet" type="text/css" href="/static/css/video-js.min.css">
    <style>
        .video-js .vjs-big-play-button{
            top: 50%;
            left: 50%;
        }
    </style>

{% endblock %}
{% block bread %}
<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="/">首页</a>></li>
                <li><a href="{% url 'course:list' %}">公开课程</a>></li>
				<li><a href="{% url 'course:detail' course.id %}">{{ course.name }}</a>></li>
				<li>{{ all_videos.name }}</li>
			</ul>
		</div>
	</div>
{% endblock %}
{% block content %}

<div id="main">
    <div style="width:1200px;height:675px; margin-left: 34px">
        <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="1200"
              poster="http://video-js.zencoder.com/oceans-clip.png"
              data-setup="{}">
            <source src="{{ all_videos.url }}" type='video/mp4'>
        </video>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'course:lesson' course.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'course:comment' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>
                </div>

                <div class="mod-chapters">
                    {% for lesson in course.get_lesson %}
                      <div class="chapter chapter-active" >
                        <h3>
                            <span class="aui-iconfont aui-icon-move"></span>
                            <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                        </h3>
                        <ul class="video">
                            {% for video in lesson.get_lesson_video %}

                            <li>
                                <a target="_blank" href='{% url "course:video_play" video.id %}' class="J-media-item studyvideo">{{ video.name }} ({{ video.learn_times }})
                                    <i class="study-state"></i>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endfor %}
                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for cour in course_resc %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ cour.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ cour.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.you_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>
                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                    {% for relater_cour in relater_courses %}
                                        <li class="curr">
                                        <a href="{% url 'course:detail' relater_cour.id %}" target="_blank">
                                            <img src="{{ MEDIA_URL }}{{ relater_cour.image }}" alt="{{ relater_cour.name }}">
                                            <span class="name autowrap">{{ relater_cour.name }}</span>
                                        </a>
                                    </li>

                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>
{% endblock %}
{% block custom_js %}
 <script src="/static/js/video.min.js" type="text/javascript"></script>
{% endblock %}

mxonline_chen/templates/org-detail-desc.html
{% extends 'org_base.html' %}
{% load staticfiles %}
{% block title %}
机构介绍
{% endblock %}
{% block bread %}
机构介绍
{% endblock %}
{% block right_form %}
<div class="right companycenter layout" >
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">
<p>{{ course_org.desc }}</p>
        </div>
    </div>
{% endblock %}

mxonline_chen/templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}
	慕课网 - 慕学网
	{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}
    
    {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %}
    
    {% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
       <div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>33333333</b></p></div>
					<!--登录后跳转-->

                        {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}<img class="down fr" src="{% static "/images/top_down.png" %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ request.user.nick_name }}</h2>
	                                    <p>{{ request.user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:userinfo' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'users:mymessage' %}">
                            <div class="msg-num"> <span id="MsgNum">{{ request.user.get_unread_nums }}</span></div>
                        </a>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}


				</div>
			</div>

    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
            <div class="head fl">
                <h1>
                    {{ course_org.name }}
                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 "data-favid="22" data-fav-type="1">
                {% if has_fav %}
                 已收藏
                {% else %}
                    收藏
                {% endif %}


            </div>

        </div>
    </div>
			</div>
    </header>
</section>

<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url 'org:list'%}">课程机构</a>></li>
			<li>{% block bread %}机构首页{% endblock %}</li>
		</ul>
	</div>
</section>



<section>
	<div class="wp list personal_list comp">

        <div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a href="{% url 'org:org_teacher' course_org.id %}">机构讲师</a></li>
			</ul>
		</div>

		{% block right_form %}

		{% endblock %}

    </div>
</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">

        //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url "org:add_fav" %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="/login/";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ course_org.id }}, 2);
});



$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static "images/" %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>

mxonline_chen/templates/usercenter-fav-course.html
{% extends 'usercenter.html' %}
{% load staticfiles %}
{% block title %}
个人中心-我的收藏课程
{% endblock %}
{% block custom_bread %}
我的收藏
{% endblock %}
{% block comment %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                     <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li ><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in courses_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:detail' course.id %}">
                                <img width="214" height="190" class="scrollLoading" data-url="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>

                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
{% endblock %}

mxonline_chen/templates/usercenter-fav-org.html
{% extends 'usercenter.html' %}
{% load staticfiles %}
{% block title %}
个人中心-我的收藏机构
{% endblock %}
{% block custom_bread %}
我的收藏
{% endblock %}
{% block comment %}
   <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active" ><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for orgs in orgs_list %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_home' orgs.id %}">
                                    <img width="160" height="90" class="scrollLoading" data-url="{{ MEDIA_URL }}{{ orgs.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:org_home' orgs.id %}">{{ orgs.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ orgs.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ orgs.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}